export const CART_REQUEST = "CART_REQUEST";

export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"; 

export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS"
export const DELETE_CART_PRODUCT_SUCCESS = "DELETE_CART_PRODUCT_SUCCESS"
export const UPDATE_CART_PRODUCT_SUCCESS = "UPDATE_CART_PRODUCT_SUCCESS"

export const CART_FAILURE = "CART_FAILURE";
