export const CART_REQUEST = "CART_REQUEST";

export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"; 

export const CART_FAILURE = "CART_FAILURE";
